import type { Career } from "./types";

export const careers: Career[] = [
  { id: "operations", title: "Operations Coordinator", description: "Keep people, schedules, and resources aligned across daily operations.", tags: ["operations", "leadership", "project"], requiredSkills: ["Operations planning", "Cross-functional team leadership", "Compliance documentation"], credentials: [], workModes: ["On-site", "Hybrid", "Flexible"] },
  { id: "logistics", title: "Logistics Coordinator", description: "Coordinate shipments, inventory, carriers, and delivery timelines.", tags: ["logistics", "supply", "operations"], requiredSkills: ["Supply-chain coordination", "Inventory control and audit readiness", "Transportation operations coordination"], credentials: [], workModes: ["On-site", "Hybrid", "Flexible"] },
  { id: "fleet", title: "Fleet Supervisor", description: "Guide vehicle readiness, dispatch, safety, and driver performance.", tags: ["fleet", "safety", "leadership"], requiredSkills: ["Fleet readiness management", "Operational risk management", "Cross-functional team leadership"], credentials: ["Commercial Driver License"], workModes: ["On-site", "Flexible"] },
  { id: "supply", title: "Supply-Chain Specialist", description: "Improve material flow, inventory accuracy, and supplier coordination.", tags: ["supply", "logistics", "project"], requiredSkills: ["Supply-chain coordination", "Inventory systems administration", "Compliance documentation"], credentials: [], workModes: ["On-site", "Hybrid", "Remote", "Flexible"] },
  { id: "emergency", title: "Emergency-Management Specialist", description: "Support preparedness, continuity, response, and recovery planning.", tags: ["emergency", "operations", "safety"], requiredSkills: ["Operational risk management", "Emergency response coordination", "Operations planning"], credentials: ["FEMA introductory coursework"], workModes: ["On-site", "Hybrid", "Flexible"] },
  { id: "project", title: "Project Coordinator", description: "Track plans, stakeholders, risks, and delivery milestones.", tags: ["project", "operations", "leadership"], requiredSkills: ["Operations planning", "Compliance documentation", "Cross-functional team leadership"], credentials: [], workModes: ["On-site", "Hybrid", "Remote", "Flexible"] },
  { id: "training", title: "Training Specialist", description: "Build and deliver workforce learning and readiness programs.", tags: ["training", "leadership", "project"], requiredSkills: ["Workforce training and readiness", "Cross-functional team leadership", "Compliance documentation"], credentials: [], workModes: ["On-site", "Hybrid", "Remote", "Flexible"] },
  { id: "safety", title: "Occupational Safety Specialist", description: "Strengthen workplace safety, reporting, and risk controls.", tags: ["safety", "training", "operations"], requiredSkills: ["Operational risk management", "Safety and response training", "Compliance documentation"], credentials: ["OSHA fundamentals coursework"], workModes: ["On-site", "Hybrid", "Flexible"] },
  { id: "healthcare", title: "Healthcare Operations Coordinator", description: "Coordinate care operations, readiness, records, and resources.", tags: ["healthcare", "operations", "customer"], requiredSkills: ["Healthcare readiness administration", "Emergency response coordination", "Internal customer service"], credentials: [], workModes: ["On-site", "Hybrid", "Flexible"] },
  { id: "field", title: "Field Operations Specialist", description: "Support customers, teams, equipment, and service delivery in the field.", tags: ["customer", "operations", "safety"], requiredSkills: ["Operations coordination", "Internal customer service", "Quality and readiness assurance"], credentials: [], workModes: ["On-site", "Hybrid", "Flexible"] },
];
