import type { Course } from "./types";

export const courses: Course[] = [
  { id: "c1", title: "Project Coordination Foundations", provider: "WayPoint Partner Academy", description: "Practice project scoping, schedules, stakeholders, and status reporting.", skillTags: ["project", "operations"], format: "Self-paced · 6 hours", funding: "Demo: potentially funded", sourcePlaceholder: "Source placeholder — verify current program and eligibility", demonstrationData: true },
  { id: "c2", title: "Supply Chain Essentials", provider: "Community Skills Network", description: "Build foundational vocabulary in inventory, procurement, and logistics flow.", skillTags: ["logistics", "supply"], format: "Online cohort · 4 weeks", funding: "Demo: no-cost pathway", sourcePlaceholder: "Source placeholder — verify current program and eligibility", demonstrationData: true },
  { id: "c3", title: "Workplace Safety Fundamentals", provider: "Regional Workforce Lab", description: "Explore hazard identification, controls, incident reporting, and safety culture.", skillTags: ["safety", "operations"], format: "Self-paced · 8 hours", funding: "Demo: workforce-funded", sourcePlaceholder: "Source placeholder — verify current program and eligibility", demonstrationData: true },
  { id: "c4", title: "Emergency Preparedness Basics", provider: "Public Service Learning Hub", description: "Learn the structure of civilian preparedness and continuity planning.", skillTags: ["emergency", "safety"], format: "Online · 5 hours", funding: "Demo: free", sourcePlaceholder: "Source placeholder — verify current program and eligibility", demonstrationData: true },
  { id: "c5", title: "Healthcare Operations Primer", provider: "Allied Health Pathways", description: "Translate readiness experience into patient-flow and healthcare administration concepts.", skillTags: ["healthcare", "operations"], format: "Hybrid · 2 weeks", funding: "Demo: scholarship-supported", sourcePlaceholder: "Source placeholder — verify current program and eligibility", demonstrationData: true },
  { id: "c6", title: "Customer Success in the Field", provider: "Service Careers Collaborative", description: "Practice discovery, expectation setting, escalation, and service recovery.", skillTags: ["customer", "operations"], format: "Self-paced · 4 hours", funding: "Demo: free", sourcePlaceholder: "Source placeholder — verify current program and eligibility", demonstrationData: true },
];
