import type { CourseRecord } from "./companion-types";

const disclaimer = "Availability and pricing vary by provider. Verify details before enrolling. Demonstration catalog.";
export const companionCourses: CourseRecord[] = [
  { id:"osha30", title:"OSHA 30-Hour Construction Outreach Training", provider:"OSHA-authorized training provider", gap:"Construction hazards, OSHA terminology, supervisor-level safety awareness", reason:"It addresses Marcus’s largest terminology and construction-workflow gap.", gain:"Stronger construction hazard vocabulary and supervisor-level awareness.", points:8, url:"https://www.osha.gov/training/outreach", lastChecked:"2026-07-18", disclaimer:`${disclaimer} Outreach Training completion card—not an OSHA certification. Cost/status: provider dependent.` },
  { id:"li-health", title:"Construction Management: Safety and Health", provider:"LinkedIn Learning", gap:"Construction safety-management systems and the role of construction managers", reason:"Connects existing operational leadership with civilian safety-management systems.", gain:"Better understanding of construction-manager safety responsibilities.", points:5, url:"https://www.linkedin.com/learning/", lastChecked:"2026-07-18", disclaimer },
  { id:"li-safety", title:"Construction Industry: Safety", provider:"LinkedIn Learning", gap:"Jobsite hazard awareness and communication between trades", reason:"Builds trade-to-trade communication context for site coordination.", gain:"Improved jobsite hazard recognition and communication.", points:4, url:"https://www.linkedin.com/learning/", lastChecked:"2026-07-18", disclaimer },
  { id:"coursera", title:"Introduction to OSHA: Safety Standards and Compliance", provider:"Coursera", gap:"Civilian compliance vocabulary and OSHA framework", reason:"Gives civilian names to concepts Marcus has practiced in structured environments.", gain:"More confident OSHA-framework vocabulary.", points:4, url:"https://www.coursera.org/", lastChecked:"2026-07-18", disclaimer },
  { id:"udemy", title:"Construction Health and Safety Management", provider:"Udemy", gap:"Site-safety practices, hazard control, and safety-management documentation", reason:"Adds documentation and hazard-control practices to existing field awareness.", gain:"Stronger site documentation and control-planning familiarity.", points:4, url:"https://www.udemy.com/", lastChecked:"2026-07-18", disclaimer },
];
