import { Check, Edit3, ShieldCheck, X } from "lucide-react";
import { demoMember } from "@/lib/waypoint/demo-member";
import { useCompanion } from "./companion-shell";
import { ReadinessMeter } from "./readiness-meter";
import { Badge, WorkspaceTitle } from "./workspace-parts";

export function TranslateWorkspace(){
 const {state,setState}=useCompanion();
 const updateSkill=(id:string,patch:Partial<(typeof state.skills)[number]>)=>setState(current=>({...current,skills:current.skills.map(skill=>skill.id===id?{...skill,...patch}:skill),lastReadinessAction:"Updated translated profile"}));
 return <div><WorkspaceTitle step="01 · Translate" title="Turn experience into safety language." description="Review a credible bridge from Marcus’s combined Army and warehouse experience into construction safety."><Badge>Synthetic demonstration profile</Badge></WorkspaceTitle>
 <ReadinessMeter/>
 <section className="target-banner"><div><small>Primary target</small><h2>{demoMember.targetCareer}</h2><p>{demoMember.targetEmployers}</p></div><div><small>Estimated target range</small><strong>{demoMember.targetSalary}</strong><p>Estimated target range for demonstration purposes. Compensation varies by role, experience, employer, and location.</p><span>Salary source: synthetic planning estimate · not market-verified</span></div></section>
 <div className="companion-grid two">
  <section className="companion-panel"><div className="panel-head"><div><small>Safety-field profile</small><h2>Professional summary</h2></div><button className={state.profileApproved?"control approved": "control"} onClick={()=>setState(current=>({...current,profileApproved:!current.profileApproved,lastReadinessAction:!current.profileApproved?"Approved translated profile":"Reopened profile review"}))}><Check size={14}/>{state.profileApproved?"Approved":"Approve profile"}</button></div><textarea className="editor large" value={state.summary} onChange={event=>setState(current=>({...current,summary:event.target.value,lastReadinessAction:"Edited professional summary"}))}/></section>
  <section className="companion-panel advisory-panel"><div className="panel-head"><div><small>Advisory</small><h2>Consultant note</h2></div><Badge tone="gold">Editable · advisory only</Badge></div><textarea className="editor large" value={state.consultantNote} onChange={event=>setState(current=>({...current,consultantNote:event.target.value,lastReadinessAction:"Edited consultant note"}))}/></section>
 </div>
 <section className="companion-panel"><div className="panel-head"><div><small>Evidence translation</small><h2>Construction-safety capabilities</h2></div><span>{state.skills.filter(skill=>skill.status==="approved"||skill.status==="edited").length} reviewed</span></div><div className="capability-list">{state.skills.map(skill=><article className={`capability-row ${skill.status}`} key={skill.id}><div className="confidence"><strong>{skill.confidence}%</strong><small>confidence</small></div><div className="capability-copy"><Badge tone={skill.source==="Military"?"":"gold"}>{skill.source} evidence</Badge><input aria-label={`Civilian skill name for ${skill.name}`} value={skill.name} onChange={event=>updateSkill(skill.id,{name:event.target.value,status:"edited"})}/><textarea aria-label={`Description for ${skill.name}`} value={skill.description} onChange={event=>updateSkill(skill.id,{description:event.target.value,status:"edited"})}/><p><strong>Source:</strong> {skill.evidence}</p></div><div className="vertical-actions"><span className={`status-pill ${skill.status}`}>{skill.status}</span><button onClick={()=>updateSkill(skill.id,{status:"approved"})}><Check size={14}/>Approve</button><button onClick={()=>updateSkill(skill.id,{status:"edited"})}><Edit3 size={14}/>Edit</button><button onClick={()=>updateSkill(skill.id,{status:"rejected"})}><X size={14}/>Reject</button></div></article>)}</div></section>
 <section className="companion-panel why-panel"><div><ShieldCheck/><h2>Why this target?</h2></div><dl><div><dt>Military evidence</dt><dd>Risk assessments, recurring briefings, procedure enforcement, incident documentation, emergency response, and team accountability.</dd></div><div><dt>Civilian evidence</dt><dd>Warehouse supervision, PPE monitoring, near-miss records, loading coordination, onboarding, and shift documentation.</dd></div><div><dt>Remaining gaps</dt><dd>OSHA construction terminology, formal inspection records, contractor workflows, and construction-specific training.</dd></div><div><dt>Why non-security</dt><dd>The repeated pattern is prevention, training, documentation, coordination, and hazard control—not guarding people or property.</dd></div><div><dt>Confidence explanation</dt><dd>Confidence reflects strength and repetition of supplied evidence, not employer validation or hiring eligibility.</dd></div></dl></section>
 <StoryBank/>
 </div>;
}
function StoryBank(){const {state,setState}=useCompanion();return <section className="companion-panel"><div className="panel-head"><div><small>Evidence provenance</small><h2>Editable Army story bank</h2></div><Badge tone="gold">Synthetic prompts until confirmed</Badge></div><div className="story-grid">{state.stories.map(story=><article className="story-card" key={story.id}><Badge>Synthetic demo story</Badge>{(["situation","task","action","result","measurableOutcome","source"] as const).map(field=><label key={field}><span>{field.replace("measurableOutcome","Measurable outcome")}</span><textarea value={story[field]} onChange={event=>setState(current=>({...current,stories:current.stories.map(item=>item.id===story.id?{...item,[field]:event.target.value}:item),lastReadinessAction:"Edited story bank"}))}/></label>)}<label className="confirm-check"><input type="checkbox" checked={story.userConfirmed} onChange={event=>setState(current=>({...current,stories:current.stories.map(item=>item.id===story.id?{...item,userConfirmed:event.target.checked}:item),lastReadinessAction:event.target.checked?"Confirmed a story as member-provided":"Removed story confirmation"}))}/> User-confirmed experience</label><small>Generated prompt is not treated as Marcus’s real experience until confirmed.</small></article>)}</div></section>}
